/**
 * Tier 2 — the middle band. DESIGN.md §6.
 *
 * Sourced from the manga: p21 (arrays), p32 (times tables), p34 (place value), p41 (remainders),
 * p45 (the two-step). This is the band the game spends most of its running time in — 33 of the
 * 104 moves sit here — so it carries the widest spread of kinds.
 *
 * `12 × 7 = ?` is the question printed on the equation strip in
 * `reference/visual/math-combat-reference.png`. It is generated by the first template below and
 * is drawn the same way, `×` included; the reference is binding and the strip has to be able to
 * render its own screenshot.
 */
import type { Rng } from '../../core/rng.ts';
import type { QuestionDraft, QuestionTemplate } from '../question.ts';
import { DENOMINATOR_WORDS, OP, PLACE_NAMES, explainProduct } from './shared.ts';

/** Tables to 12, both ways round, with an `array` visual for the p21 rows-of-dots reading. */
function timesTable(rng: Rng): QuestionDraft {
  const a = rng.int(2, 12);
  const b = rng.int(2, 12);
  return {
    kind: 'times-table',
    prompt: `${a} ${OP.times} ${b} = ?`,
    answer: a * b,
    explain: `${explainProduct(a, b)}.`,
    visual: { kind: 'array', data: { rows: a, cols: b } },
  };
}

/**
 * Division with remainders — p41's "87 props, 4 galleries".
 *
 * The keypad produces one number, so the question asks for one half of `21 r3` at a time and the
 * working always shows both. Splitting it is not a dodge: "how many each" and "how many left
 * over" are the two questions a remainder is actually *for*.
 */
function divisionRemainder(rng: Rng): QuestionDraft {
  const divisor = rng.int(3, 9);
  const remainder = rng.int(1, divisor - 1);
  // Keep the dividend inside two digits — three-digit division is the Tier 3 band's business.
  const maxQuotient = Math.min(24, Math.floor((99 - remainder) / divisor));
  const quotient = rng.int(4, maxQuotient);
  const total = divisor * quotient + remainder;
  const askEach = rng.chance(0.6);
  const explain = `${divisor} ${OP.times} ${quotient} = ${divisor * quotient}, and ${total} ${OP.minus} ${divisor * quotient} = ${remainder}. So ${total} ${OP.divide} ${divisor} = ${quotient} r${remainder}.`;
  return {
    kind: 'division-remainder',
    prompt: `${total} ${OP.divide} ${divisor} → ${askEach ? 'each' : 'left over'} = ?`,
    answer: askEach ? quotient : remainder,
    explain,
  };
}

/**
 * `The 5 in 456 is worth ?` — p34.
 *
 * The chosen digit is guaranteed to appear exactly once. "The 5 in 455" has two answers and no
 * amount of good intent at the keypad can fix that.
 */
function placeValue(rng: Rng): QuestionDraft {
  const length = rng.int(3, 4);
  const target = rng.int(1, 9);
  const position = rng.int(0, length - 1);

  const digits: number[] = [];
  for (let i = 0; i < length; i++) {
    if (i === position) {
      digits.push(target);
      continue;
    }
    const low = i === 0 ? 1 : 0;
    let digit = rng.int(low, 9);
    // Redraw rather than shift: shifting would bias the other digits away from `target ± 1`.
    while (digit === target) digit = rng.int(low, 9);
    digits.push(digit);
  }

  const number = Number(digits.join(''));
  const power = length - 1 - position;
  const worth = target * 10 ** power;
  const parts = digits
    .map((d, i) => d * 10 ** (length - 1 - i))
    .filter((v) => v > 0)
    .join(` ${OP.plus} `);

  return {
    kind: 'place-value',
    prompt: `The ${target} in ${number} is worth ?`,
    answer: worth,
    explain: `${number} = ${parts}. The ${target} sits in the ${PLACE_NAMES[power] ?? 'ones'} column, so it is worth ${worth}.`,
  };
}

/** `Half of 46 = ?` — partition, halve each part, recombine. */
function halving(rng: Rng): QuestionDraft {
  const n = rng.int(6, 49) * 2;
  const tens = Math.floor(n / 10) * 10;
  const ones = n % 10;
  return {
    kind: 'halving',
    prompt: `Half of ${n} = ?`,
    answer: n / 2,
    explain: `Half of ${tens} is ${tens / 2}, half of ${ones} is ${ones / 2}. ${tens / 2} ${OP.plus} ${ones / 2} = ${n / 2}.`,
  };
}

/** `Double 34 = ?` — the same partition, run the other way. */
function doubling(rng: Rng): QuestionDraft {
  const n = rng.int(11, 60);
  const tens = Math.floor(n / 10) * 10;
  const ones = n % 10;
  return {
    kind: 'doubling',
    prompt: `Double ${n} = ?`,
    answer: n * 2,
    explain: `Double ${tens} is ${tens * 2}, double ${ones} is ${ones * 2}. ${tens * 2} ${OP.plus} ${ones * 2} = ${n * 2}.`,
  };
}

/** `6 × 4 + 7 = ?` — p45. Order of operations, stated in the working every time. */
function twoStep(rng: Rng): QuestionDraft {
  const a = rng.int(2, 9);
  const b = rng.int(2, 9);
  const c = rng.int(1, 20);
  const product = a * b;
  return {
    kind: 'two-step',
    prompt: `${a} ${OP.times} ${b} ${OP.plus} ${c} = ?`,
    answer: product + c,
    explain: `${a} ${OP.times} ${b} = ${product} first, then ${product} ${OP.plus} ${c} = ${product + c}. Multiply before you add.`,
  };
}

/**
 * `1/2 = ? sixths` — equivalent fractions as a count, because the keypad has no fraction bar.
 *
 * The numerator is what the player types, so the question is "how many of these smaller parts",
 * which is the same reasoning as the fraction wall and needs no new notation.
 */
const BASE_FRACTIONS: readonly (readonly [number, number])[] = [
  [1, 2],
  [1, 3],
  [2, 3],
  [1, 4],
  [3, 4],
  [1, 5],
  [2, 5],
  [3, 5],
  [4, 5],
];

function equivalentFraction(rng: Rng): QuestionDraft {
  const [num, den] = rng.pick(BASE_FRACTIONS);
  const k = rng.int(2, 4);
  const newDen = den * k;
  const answer = num * k;
  const word = DENOMINATOR_WORDS[newDen] ?? `${newDen}ths`;
  return {
    kind: 'equivalent-fraction',
    prompt: `${num}/${den} = ? ${word}`,
    answer,
    explain: `${num}/${den} = ${answer}/${newDen} — multiply top and bottom by ${k}. That is ${answer} ${word}.`,
  };
}

export const TIER2_TEMPLATES: readonly QuestionTemplate[] = [
  { kind: 'times-table', weight: 5, make: timesTable },
  { kind: 'division-remainder', weight: 3, make: divisionRemainder },
  { kind: 'place-value', weight: 2, make: placeValue },
  { kind: 'halving', weight: 2, make: halving },
  { kind: 'doubling', weight: 2, make: doubling },
  { kind: 'two-step', weight: 3, make: twoStep },
  { kind: 'equivalent-fraction', weight: 2, make: equivalentFraction },
];
